# Generated by Django 3.2.12 on 2023-03-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('cat_image', models.ImageField(upload_to='images/categories/')),
                ('cat_desc', models.CharField(max_length=100)),
                ('cat_active', models.BooleanField(default=True)),
                ('cat_created_at', models.DateTimeField(auto_now=True)),
                ('cat_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('sub_image', models.ImageField(upload_to='images/subCategories')),
                ('sub_desc', models.CharField(max_length=100)),
                ('sub_active', models.BooleanField(default=True)),
                ('sub_created_at', models.DateTimeField(auto_now=True)),
                ('sub_updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Super_Category', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_image', models.ImageField(upload_to='images/subCategories')),
                ('item_desc', models.CharField(max_length=100)),
                ('item_price', models.PositiveIntegerField(default=0)),
                ('item_active', models.BooleanField(default=True)),
                ('item_created_at', models.DateTimeField(auto_now=True)),
                ('item_updated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_subCategory', to='shop.subcategory')),
            ],
        ),
    ]
