# Generated by Django 3.2.12 on 2023-03-10 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20230306_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_by_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
