# Generated by Django 3.2.12 on 2023-03-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
    ]
